### ISSUE TITLE
Transposing chords with added bass notes

### ISSUE THREAD

**Issue by nuncaeslupus** [frescobaldi/quickly#3]
When transposing a chord which has an added bass note, if the destination pitch is lower than the original one and the bass note moves to a lower octave, the transposition adds one (or more) `','` after the bass note. I think that is not allowed in lilypond or the parser doesn't know how to manage it, because it returns an `Unknown token` error. It does not happen when the transposition moves one or more octaves up.

```python
import parce
from quickly.registry import find
from quickly.pitch import Pitch
from quickly.transpose import transpose, Transposer

text = r"\relative c' {\chordmode { g:7 | c2/e }}" # Chord with bass note
doc = parce.Document(find("lilypond"), transformer=True)
doc.set_text(text)

print(doc.text()) # \relative c' {\chordmode { g:7 | c2/e }}

pitch1 = Pitch(0, 0, 0)
pitch2 = Pitch(-1, 0, 0) # Transpose exactly one octave down
t = Transposer(pitch1, pitch2)
transpose(doc, t) # Unknown token: <Token ',' at 39:40 (Delimiter)>

print(doc.text()) # \relative c { \chordmode { g':7 | c'2/e, } }
```
Also, shouldn't chord notes be also transposed down? I mean, `g`instead of `g'`. Without using `\relative`you get the same result.

**Comment by wbsoft** [comment]
Indeed in chordmode the note should be transposed, but the added base note not. Thanks for reporting!
