### ISSUE TITLE
rel2abs and abs2rel behave abnormally

### ISSUE THREAD

**Issue by nuncaeslupus** [frescobaldi/quickly#4]
When following and trying the _Features of quickly_ section from [quick-ly.info](https://quick-ly.info/features.html), I can't get the results that `rel2abs`and `abs2rel`are supposed to return. This is the code:

```python
import parce
from quickly.registry import find
from quickly.relative import rel2abs, abs2rel

text = r"music = \relative c' { c d e f g }"
doc = parce.Document(find("lilypond"), text, transformer=True)

print(doc.text()) # music = \relative c' { c d e f g }
rel2abs(doc)
print(doc.text()) # music = c' { c d, e,, f,,, g,,,, }
abs2rel(doc)
print(doc.text())
# music = c
# 
# \relative c' { c d, e, f, g, }
```

Maybe some recent change?

Thanks!

**Comment by wbsoft** [comment]
Thanks for reporting, strange that this bug slipped though the tests...!

**Comment by nuncaeslupus** [comment]
Thanks for both corrections, it works like a charm now!
